'''strategy.py

Algorithmic day‑trading signal generator.

Provides a single public function `generate_signals(df)` that calculates a fast (9‑period) EMA,
slow (21‑period) EMA, and a 14‑period RSI using the `pandas_ta` library.  The most recent candle
is examined for a bullish EMA crossover combined with an RSI filter (40‑70) to emit a **BUY**
signal, a bearish EMA crossover to emit a **SELL** signal, otherwise **HOLD**.

The function returns a dictionary containing the signal string and the exact latest values of
the three indicators for logging or reporting purposes.
'''\n\nimport pandas as pd\nimport pandas_ta as ta\n\n\ndef _validate_dataframe(df: pd.DataFrame) -> None:\n    """Validate input DataFrame.\n\n    Raises:\n        ValueError: If `df` is empty, missing required columns, or lacks enough rows for the 21‑period EMA.\n    """\n    required_cols = {"open", "high", "low", "close", "volume"}\n    if df.empty:\n        raise ValueError("Input DataFrame is empty.")\n    missing = required_cols - set(df.columns)\n    if missing:\n        raise ValueError(f"DataFrame missing required columns: {missing}")\n    # At least 21 rows are needed for the longest EMA window (21 periods).\n    if len(df) < 21:\n        raise ValueError("DataFrame must contain at least 21 rows for EMA calculation.")\n\n\ndef generate_signals(df: pd.DataFrame) -> dict:\n    """Generate a trading signal from 5‑minute candlestick data.\n\n    Parameters\n    ----------\n    df : pandas.DataFrame\n        Historical candlestick data with columns: ``open``, ``high``, ``low``, ``close``,
        and ``volume``.  The DataFrame should be ordered chronologically, newest row last.\n\n    Returns\n    -------\n    dict\n        ``{"signal": str, "ema9": float, "ema21": float, "rsi": float}`` where ``signal`` is\n        one of ``"BUY"``, ``"SELL"`` or ``"HOLD"``.\n\n    Notes\n    -----\n    * Bullish EMA crossover (9‑EMA crossing above 21‑EMA) **and** RSI in the inclusive range\n      ``[40, 70]`` → **BUY**.\n    * Bearish EMA crossover (9‑EMA crossing below 21‑EMA) → **SELL** (RSI ignored).\n    * All other states → **HOLD**.\n    """\n    # 1️⃣ Validate input\n    _validate_dataframe(df)\n\n    # 2️⃣ Compute indicators using pandas_ta\n    df["EMA9"] = ta.ema(df["close"], length=9)\n    df["EMA21"] = ta.ema(df["close"], length=21)\n    df["RSI14"] = ta.rsi(df["close"], length=14)\n\n    # 3️⃣ Grab latest and previous rows for crossover detection\n    latest = df.iloc[-1]\n    prev = df.iloc[-2]\n\n    ema9_latest = latest["EMA9"]\n    ema21_latest = latest["EMA21"]\n    rsi_latest = latest["RSI14"]\n\n    ema9_prev = prev["EMA9"]\n    ema21_prev = prev["EMA21"]\n\n    # 4️⃣ Decision logic\n    signal = "HOLD"\n    # Bullish crossover + RSI filter\n    if ema9_prev <= ema21_prev and ema9_latest > ema21_latest and 40 <= rsi_latest <= 70:\n        signal = "BUY"\n    # Bearish crossover (no RSI condition)\n    elif ema9_prev >= ema21_prev and ema9_latest < ema21_latest:\n        signal = "SELL"\n\n    # 5️⃣ Return values rounded for readability\n    return {\n        "signal": signal,\n        "ema9": round(float(ema9_latest), 4),\n        "ema21": round(float(ema21_latest), 4),\n        "rsi": round(float(rsi_latest), 2),\n    }\n\n# Example usage (remove when integrating into production):\n# if __name__ == "__main__":\n#     import numpy as np\n#     np.random.seed(0)\n#     data = {\n#         "open": np.random.rand(30),\n#         "high": np.random.rand(30),\n#         "low": np.random.rand(30),\n#         "close": np.random.rand(30),\n#         "volume": np.random.rand(30),\n#     }\n#     df_demo = pd.DataFrame(data)\n#     print(generate_signals(df_demo))\n
